import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Share } from '@capacitor/share';
import { Filesystem, Directory } from '@capacitor/filesystem';
import { Capacitor } from '@capacitor/core';

export const generatePDFReport = async (type, user, data) => {
    const doc = new jsPDF();
    const { transactions, tasks, journals, studySessions } = data;
    const dateRange = type === 'weekly' ? 'Last 7 Days' : 'Last 30 Days';
    const date = new Date().toLocaleDateString();

    // -- Header --
    doc.setFillColor(15, 15, 26); // Dark background
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("Personal Growth Report", 14, 20);

    doc.setFontSize(12);
    doc.setTextColor(168, 85, 247); // Primary purple
    doc.text(`${type.charAt(0).toUpperCase() + type.slice(1)} Summary • ${dateRange}`, 14, 30);

    doc.setFontSize(10);
    doc.setTextColor(200, 200, 200);
    doc.text(`Generated for: ${user.name}`, 150, 20);
    doc.text(`Date: ${date}`, 150, 26);

    let yPos = 50;

    // -- Section 1: Finances --
    const totalIncome = transactions
        .filter(t => t.type === 'income')
        .reduce((acc, t) => acc + t.amount, 0);

    const totalExpense = transactions
        .filter(t => t.type === 'expense')
        .reduce((acc, t) => acc + t.amount, 0);

    const savings = totalIncome - totalExpense;

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.text("1. Financial Overview", 14, yPos);
    yPos += 10;

    autoTable(doc, {
        startY: yPos,
        head: [['Category', 'Amount']],
        body: [
            ['Total Income', `Rp ${totalIncome.toLocaleString()}`],
            ['Total Expense', `Rp ${totalExpense.toLocaleString()}`],
            ['Net Savings', `Rp ${savings.toLocaleString()}`],
        ],
        theme: 'grid',
        headStyles: { fillColor: [249, 115, 22] }, // Orange
    });

    yPos = doc.lastAutoTable.finalY + 20;

    // -- Section 2: Productivity --
    const totalTasks = tasks.length;
    const completedTasks = tasks.filter(t => t.completed).length;
    const completionRate = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;

    doc.text("2. Productivity & Tasks", 14, yPos);
    yPos += 10;

    autoTable(doc, {
        startY: yPos,
        head: [['Metric', 'Value']],
        body: [
            ['Total Tasks', totalTasks],
            ['Completed', completedTasks],
            ['Completion Rate', `${completionRate}%`],
        ],
        theme: 'grid',
        headStyles: { fillColor: [0, 212, 255] }, // Blue
    });

    yPos = doc.lastAutoTable.finalY + 20;

    // -- Section 3: Learning --
    const totalStudyMins = studySessions.reduce((acc, s) => acc + s.duration, 0);
    const totalHours = (totalStudyMins / 60).toFixed(1);

    doc.text("3. Learning Journey", 14, yPos);
    yPos += 10;

    autoTable(doc, {
        startY: yPos,
        head: [['Activity', 'Duration']],
        body: [
            ['Total Study Sessions', studySessions.length],
            ['Total Focus Time', `${totalHours} Hours`],
        ],
        theme: 'grid',
        headStyles: { fillColor: [20, 184, 166] }, // Teal
    });

    yPos = doc.lastAutoTable.finalY + 20;

    // -- Footer --
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by SuperApp Premium AI", 14, 280);

    // Save Logic
    const fileName = `${user.username}_${type}_report_${Date.now()}.pdf`;

    if (Capacitor.isNativePlatform()) {
        try {
            const base64Data = doc.output('datauristring').split(',')[1];

            await Filesystem.writeFile({
                path: fileName,
                data: base64Data,
                directory: Directory.Cache
            });

            const uriResult = await Filesystem.getUri({
                directory: Directory.Cache,
                path: fileName
            });

            await Share.share({
                title: 'Smart Report',
                text: 'Here is your generated report.',
                url: uriResult.uri,
                dialogTitle: 'Open PDF with...'
            });

        } catch (e) {
            console.error('Mobile share failed', e);
            // Fallback
            doc.save(fileName);
        }
    } else {
        doc.save(fileName);
    }
};

export const generateModulePDF = async () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 15;  // Reduced from 20 to 15
    const maxLineWidth = pageWidth - margin * 2;
    let yPos = 25;  // Reduced initial position

    const checkPageBreak = (height = 15) => {
        if (yPos + height >= 280) {  // Increased from 270 to 280
            doc.addPage();
            yPos = 25;  // Reduced from 30 to 25
            // Page header - clean and readable
            doc.setFontSize(8);
            doc.setTextColor(100, 100, 100);
            doc.setFont('helvetica', 'normal');
            doc.text("Prefrontal: The Productivity SuperApp Manual", margin, 10);
            doc.setTextColor(0, 0, 0);  // Reset to black
        }
    };

    const addChapterTitle = (num, text) => {
        doc.addPage();
        yPos = 40;  // Reduced from 60
        doc.setFontSize(60);  // Reduced from 80
        doc.setTextColor(200, 200, 220);
        doc.setFont('helvetica', 'bold');
        doc.text(num, margin, yPos);

        yPos += 12;  // Reduced from 15
        doc.setFontSize(20);  // Reduced from 24
        doc.setTextColor(0, 0, 0);
        doc.text(text, margin, yPos);
        yPos += 15;  // Reduced from 20

        // Reset font
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);
    };

    const addSectionTitle = (text) => {
        checkPageBreak(35);  // Increased to ensure title + at least 2 lines of content
        yPos += 6;
        doc.setFontSize(13);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(40, 40, 50);
        doc.text(text, margin, yPos);
        yPos += 5;

        // Reset
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);
    };

    const addParagraph = (text) => {
        const lines = doc.splitTextToSize(text, maxLineWidth);
        const lineHeight = 5;  // Reduced from 6
        const height = lines.length * lineHeight;
        checkPageBreak(height + 3);  // Reduced from 5
        doc.text(lines, margin, yPos);
        yPos += height + 3;  // Reduced spacing after paragraph
    };

    const addBullet = (title, text) => {
        // Render bold title first
        doc.setFont('helvetica', 'bold');
        const bulletPrefix = `• ${title}:`;
        doc.text(bulletPrefix, margin, yPos);

        // Calculate width of the title to offset description
        const titleWidth = doc.getTextWidth(bulletPrefix) + 2;

        // Calculate remaining width for description
        const descriptionMaxWidth = maxLineWidth - titleWidth;

        // Split description text to fit in remaining width
        doc.setFont('helvetica', 'normal');
        const lines = doc.splitTextToSize(text, descriptionMaxWidth);

        // If description is short (1 line), print on same line
        if (lines.length === 1) {
            doc.text(text, margin + titleWidth, yPos);
            yPos += 6;  // Reduced from 8
        } else {
            doc.text(lines[0], margin + titleWidth, yPos);
            for (let i = 1; i < lines.length; i++) {
                yPos += 5;  // Reduced from 6
                // check page break within bullet
                if (yPos >= 280) {
                    doc.addPage();
                    yPos = 25;
                }
                doc.text(lines[i], margin, yPos);
            }
            yPos += 6;  // Reduced from 8
        }

        checkPageBreak(4);
    };

    // -- Cover Page --
    doc.setFillColor(15, 15, 26); // Midnight Blue Background
    doc.rect(0, 0, 210, 297, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(42);
    doc.setFont('helvetica', 'bold');
    doc.text("Prefrontal", 105, 100, { align: 'center' });

    doc.setFontSize(18);
    doc.setFont('helvetica', 'normal');
    doc.text("The Productivity SuperApp", 105, 115, { align: 'center' });

    doc.setFontSize(10);
    doc.text("Authored by Fathir Ramadhan", 105, 270, { align: 'center' });

    // -- Table of Contents --
    doc.addPage();
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(20);
    doc.text("Table of Contents", margin, 40);

    const chapters = [
        "1. The Philosophy",
        "2. The Dashboard",
        "3. Calendar & Tasks",
        "4. Pref AI Intelligence",
        "5. Learning Center",
        "6. Financial Cortex",
        "7. Mind & Wellness",
        "8. Atomic Habits",
        "9. Gamification",
        "10. Data & Privacy"
    ];

    yPos = 60;
    doc.setFontSize(12);
    chapters.forEach(chap => {
        doc.text(chap, margin, yPos);
        yPos += 12;
    });

    // -- Content Chapters (Comprehensive & Detailed) --

    // ========== CHAPTER 1: PHILOSOPHY ==========
    addChapterTitle("01", "The Philosophy");
    addSectionTitle("The Myth of Multitasking");
    addParagraph("The human brain is optimized for serial processing, not parallel multitasking. Modern productivity tools often fragment our attention by forcing us to switch contexts constantly—jumping from a budgeting app to a calendar, then to a habit tracker. This 'Context Switching' incurs a heavy metabolic cost, depleting glucose and reducing our functional IQ by up to 10 points according to cognitive neuroscience research.");
    addParagraph("The Prefrontal SuperApp is designed to mitigate this by unifying all essential cognitive tools into one interface. By consolidating Finance, Scheduling, Learning, Wellness, and AI into a single ecosystem, we eliminate the friction of app-switching. This allows you to enter a 'Flow State' faster and maintain it longer. The app acts as a 'Digital Prefrontal Cortex', handling executive functions so your biological brain remains free for creative and deep work.");
    addSectionTitle("Design Principles");
    addParagraph("Every feature in Prefrontal follows three core principles: 1) Reduce Cognitive Load - Present only essential information at the right time. 2) Create Frictionless Actions - Minimize steps between intention and execution. 3) Leverage Psychology - Use behavioral science to build sustainable productivity habits, not just temporary motivation.");
    addSectionTitle("Why 'Prefrontal'?");
    addParagraph("The prefrontal cortex is responsible for executive functions: planning, decision-making, impulse control, and working memory. This app digitizes those functions. When you track your finances, you're externalizing 'Financial Planning'. When you set a task reminder, you're outsourcing 'Prospective Memory'. The goal is cognitive augmentation, not replacement.");

    // ========== CHAPTER 2: DASHBOARD ==========
    addChapterTitle("02", "Home Dashboard");
    addParagraph("The Dashboard follows the principles of 'Cognitive Ergonomics'. Most interfaces bombard users with irrelevant notifications and clutter. Prefrontal's dashboard answers one critical question: 'What is my immediate state right now?' It provides maximum situational awareness with minimum cognitive load.");
    addSectionTitle("Vital Signs Cards");
    addParagraph("The top section displays three real-time metrics that give you an instant health check of your productivity ecosystem:");
    addBullet("Financial Pulse", "Displays your real-time Net Balance (Total Income minus Total Expenses). It uses color-coded visual cues: Green indicates a surplus (you're saving), Red signals a deficit (spending more than earning), and Yellow shows break-even. This triggers an immediate 'Loss Aversion' response—a psychological principle where losses feel twice as painful as equivalent gains. Seeing red naturally motivates corrective spending behavior.");
    addBullet("Task Load", "Shows the number of incomplete tasks with deadlines set for TODAY ONLY. It prevents 'Task Paralysis' by hiding future obligations and focusing your attention solely on immediate actionable items. The number turns red when exceeding 5 tasks, signaling cognitive overload.");
    addBullet("Mental Streak", "Tracks consecutive days of mood logging in the Mind & Wellness module. This leverages the 'Endowment Effect'—the psychological tendency to value what we already own. The longer your streak, the more painful it becomes to break it, creating a self-sustaining motivation loop.");
    addSectionTitle("Quick Actions Grid");
    addParagraph("Below the Vital Signs, you'll find a 2x2 grid of large, color-coded action buttons. Each button is a direct portal to a deep module: Finance (Green), Learning (Purple), Habits (Orange), Mind (Blue). This design reduces 'Time-to-Action' latency—the delay between wanting to do something and actually doing it. Instead of navigating through multiple menus, you're one tap away from your goal.");
    addSectionTitle("Dynamic Greeting");
    addParagraph("The dashboard header displays a time-aware personalized greeting: 'Good Morning, [Your Name]' (5AM-12PM), 'Good Afternoon' (12PM-5PM), or 'Good Evening' (5PM-5AM). This small touch humanizes the interface and creates a welcoming ritual every time you open the app.");

    // ========== CHAPTER 3: CALENDAR & TASKS ==========
    addChapterTitle("03", "Calendar & Tasks");
    addSectionTitle("Dual-System Architecture");
    addParagraph("Most productivity apps conflate 'Events' and 'Tasks', but the brain processes them differently. Prefrontal separates them into two distinct cognitive buckets:");
    addBullet("Event Calendar (Hard Landscape)", "For non-negotiable, time-specific commitments like 'Doctor Appointment at 2 PM' or 'Meeting with Client at 10 AM'. These are visualized on a Monthly Calendar with density dots—small colored circles appear on dates with events, allowing you to gauge your schedule density at a glance. Tapping any date reveals that day's events in chronological order.");
    addBullet("Task List (Soft Landscape)", "For flexible to-dos that just need completion, like 'Finish Report' or 'Buy Groceries'. Each task can be tagged with High (Red), Medium (Yellow), or Low (Green) priority. Completing a task triggers haptic feedback (a gentle vibration) combined with a visual checkmark animation, releasing a small dopamine reward that reinforces the behavior.");
    addSectionTitle("Adding Events");
    addParagraph("To add an event: 1) Tap the floating '+' button. 2) Enter the event title (e.g., 'Team Standup'). 3) Select the date using the calendar picker. 4) Set the time using the time wheel. 5) Optionally toggle 'Notification' to receive an alert 15 minutes before the event. The system uses native Android notifications that work even when the app is closed.");
    addSectionTitle("Adding Tasks");
    addParagraph("To add a task: 1) Tap 'Add Task' in the Tasks tab. 2) Write a clear, actionable description (e.g., 'Draft Chapter 3 of Thesis'). 3) Assign a priority level. 4) Set an optional due date for deadline tracking. Tasks without due dates remain in the 'Someday' category, preventing them from cluttering your daily view.");
    addSectionTitle("Local System Notifications");
    addParagraph("Crucially, Prefrontal includes 'Local Push Notifications'. When you set a reminder for an event or task, the app schedules an Android system notification. This means even if the app is fully closed or your phone is locked, you'll still receive the alert at the exact time. This offloads the 'Prospective Memory' function (remembering to do something in the future) from your brain to your device.");
    addSectionTitle("Recurring Events");
    addParagraph("Currently, Prefrontal supports manual creation of events. For recurring commitments (e.g., 'Monday Meetings'), simply create the event once, then duplicate it for future dates. Future updates will include one-click recurring event templates.");

    // ========== CHAPTER 4: PREF AI ==========
    addChapterTitle("04", "Pref AI Intelligence");
    addParagraph("Pref AI is not a generic chatbot—it is the Central Nervous System of Prefrontal. Powered by Google's Gemini 1.5 Pro, it offers multimodal intelligence with conversational fluency, document analysis, and contextual awareness of your personal data.");
    addSectionTitle("Contextual Awareness");
    addParagraph("Unlike standard AI assistants, Pref AI has read-access to your app state. If you ask 'Why am I stressed?', it doesn't give generic advice. Instead, it intelligently checks: (1) Your Task Load—are you overcommitted? (2) Your recent Mood Logs—have you been consistently logging negative emotions? (3) Your Financial Balance—is money pressure a factor? It then synthesizes this data into a personalized, evidence-based response.");
    addParagraph("Example queries you can ask: 'Summarize my spending this month', 'What tasks do I have today?', 'Why is my mood streak broken?', 'Give me a motivational quote for procrastination', 'How can I improve my focus for studying?'. The AI acts as a rational accountability partner, helping you debug your own life using first-principles thinking.");
    addSectionTitle("RAG Engine (PDF Analysis)");
    addParagraph("The Retrieval-Augmented Generation (RAG) engine transforms Pref AI into a 'Second Brain' for knowledge work. You can upload PDF documents—lecture slides, research papers, legal contracts, textbooks—and the AI will digest them instantly.");
    addSectionTitle("How to Use PDF Analysis");
    addParagraph("Step 1: Tap the 'paperclip' icon in the Pref AI chat interface. Step 2: Select a PDF from your device storage (max 10MB, up to 50 pages recommended for optimal performance). Step 3: The AI will process the document in 3-5 seconds. Step 4: You can now chat with the document.");
    addBullet("Summarization", "Ask 'Summarize this document in 5 bullet points' to get a rapid overview without reading the entire file. Useful for condensing academic papers or meeting notes.");
    addBullet("Interrogation", "Ask specific questions like 'What is the methodology used in Chapter 3?' or 'List all deadlines mentioned'. The AI scans the document and provides cited answers with page references.");
    addBullet("Comprehension", "Ask 'Explain the concept of X in simple terms' to break down complex jargon into beginner-friendly language.");
    addSectionTitle("Conversation Memory");
    addParagraph("Pref AI maintains conversation context within a session. You can ask follow-up questions like 'What about Y?' and it will remember you were discussing topic X. However, note that context resets when you close the app. For persistent knowledge, use the PDF upload feature.");

    // ========== CHAPTER 5: LEARNING CENTER ==========
    addChapterTitle("05", "Learning Center");
    addParagraph("The Learning Center is your 'Focus Engine', designed to facilitate Deep Work and efficient memory encoding. It combines time-management techniques with auditory focus aids and active learning tools.");
    addSectionTitle("Pomodoro Timer 2.0");
    addParagraph("Based on Francesco Cirillo's Pomodoro Technique, this timer structures your study/work sessions into focused intervals separated by short breaks. Research shows that the brain's attention span peaks around 25-45 minutes before fatigue sets in.");
    addParagraph("How to use: 1) Select your work duration (15, 25, 45, or 60 minutes). 2) Tap 'Start Focus'. The timer begins counting down. 3) Work uninterrupted until the timer rings. 4) Take a 5-minute break (or 15 minutes after 4 consecutive sessions). 5) Repeat.");
    addParagraph("When the timer completes, you'll receive a notification with a brief musical chime. This auditory signal trains your brain to associate the sound with task completion, creating a Pavlovian reward loop. Your dashboard tracks total Pomodoros completed for gamified progress.");
    addSectionTitle("Focus Soundscapes");
    addParagraph("The built-in audio engine offers 5 high-fidelity soundscapes designed to mask distracting environmental noise and induce Alpha brain waves (8-12 Hz), the frequency associated with relaxed focus:");
    addBullet("Rain", "Gentle rainfall with distant thunder. Ideal for reading or light coding work.");
    addBullet("Forest", "Ambient bird calls and rustling leaves. Perfect for creative thinking or brainstorming.");
    addBullet("Ocean Waves", "Rhythmic wave crashes. Recommended for meditation or writing.");
    addBullet("White Noise", "Pure static noise that masks sudden sounds. Best for noisy environments like cafes.");
    addBullet("Binaural Beats", "Stereo frequency tones that sync left/right brain hemispheres. Use with headphones for maximum effect.");
    addParagraph("To use: Tap the 'soundscape' icon in Learning Center, select your preferred sound, and adjust volume. Sounds loop continuously until manually stopped. You can run soundscapes simultaneously with the Pomodoro timer.");
    addSectionTitle("Study Task Manager");
    addParagraph("The Learning module includes a mini task manager specifically for study goals. Unlike the main Task module, these tasks track percentage-based progress. For example, 'Read Chapters 1-10' can be marked as 30% complete after reading 3 chapters. This visual progress bar provides incremental dopamine hits, combating procrastination on large projects.");
    addSectionTitle("Flashcard System");
    addParagraph("Passive re-reading is the least effective study method. Prefrontal uses 'Active Recall'—forcing your brain to retrieve information strengthens neural pathways. To create a flashcard: 1) Tap 'Add Flashcard'. 2) Enter the question ('What is the capital of France?'). 3) Enter the answer ('Paris'). 4) Save. To study: tap 'Review', see the question, mentally answer, then flip the card to check. Mark 'Correct' or 'Incorrect' to track mastery.");

    // ========== CHAPTER 6: FINANCIAL CORTEX ==========
    addChapterTitle("06", "Financial Cortex");
    addParagraph("Money triggers strong emotional responses—fear, guilt, greed. The Financial Cortex uses principles from Behavioral Economics to hack your spending psychology and build intuitive wealth habits.");
    addSectionTitle("Frictionless Logging Philosophy");
    addParagraph("The #1 reason budgets fail is friction. Entering transactions feels tedious, so people skip it, and the system collapses. Prefrontal's 'Speed Logger' eliminates friction: the entire input flow (Amount → Category → Save) takes under 3 seconds. The interface is optimized for thumbs, with large tap targets and auto-formatting.");
    addSectionTitle("Adding Transactions");
    addParagraph("To log an expense: 1) Tap the green '+' button. 2) Enter the amount (e.g., type '50000' and it auto-formats to 'Rp 50.000'). 3) Tap a category button (Food, Transport, Entertainment, Health, Shopping, Bills, or Other). 4) Hit 'Save'. Done. The transaction instantly appears in your timeline and updates your Net Balance card on the Dashboard.");
    addParagraph("To log income: The flow is identical, but tap 'Income' instead of 'Expense' before selecting a category. Income categories include Salary, Freelance, Investment, Gift, or Other.");
    addSectionTitle("Transaction History");
    addParagraph("The 'Transactions' tab displays a reverse-chronological feed of all financial activity. Each entry shows: Amount, Category (with color-coded icon), Date, and Type (Income/Expense). You can delete any transaction by long-pressing and confirming. Use the search bar to filter by category or date range (e.g., 'Show all Food expenses in December').");
    addSectionTitle("Financial Goals");
    addParagraph("The Goals feature helps you save toward specific targets. To create a goal: 1) Tap 'Add Goal'. 2) Name it (e.g., 'New Laptop'). 3) Set the target amount (e.g., Rp 5.000.000). 4) Optionally set a deadline. The system tracks your progress by calculating: (Current Savings / Target Amount) × 100. A visual progress bar fills as you approach your goal, providing tangible motivation.");
    addSectionTitle("Visual Analytics Tab");
    addParagraph("The 'Analytics' section transforms raw numbers into actionable insights. It includes:");
    addBullet("Donut Chart (Spending Breakdown)", "Visualizes what percentage of your expenses go to each category. If 'Food' is 50% of your pie, you know where to cut. Colors match category icons for instant recognition.");
    addBullet("Trend Line (7-Day Spending Velocity)", "A line graph showing daily spending over the past week. A steep upward slope = you're burning money fast. A flat line = stable spending. This helps you spot patterns (e.g., 'I always overspend on weekends').");
    addBullet("Income vs Expense Bar Chart", "Side-by-side monthly comparison. If the Expense bar towers over Income, you're in deficit mode. Visual comparison is faster than reading numbers.");
    addSectionTitle("Indonesian Market Optimization");
    addParagraph("Prefrontal is specifically designed for Indonesian users. All amounts use 'Rp' prefix, thousand separators (50.000 instead of 50,000), and no decimal cents (since Rupiah doesn't use them in daily transactions). Category presets reflect local spending patterns (e.g., 'Ojek Online' transport, 'Warung' food).");

    // ========== CHAPTER 7: MIND & WELLNESS ==========
    addChapterTitle("07", "Mind & Wellness");
    addSectionTitle("The Neuroscience of Emotion");
    addParagraph("The Limbic System (your 'emotional brain') often hijacks the Prefrontal Cortex (your 'rational brain'). When you're angry, sad, or anxious, you make poor decisions. The Mind module helps you regulate emotions using evidence-based techniques from psychology and neuroscience.");
    addSectionTitle("Mood Tracker");
    addParagraph("Research shows that simply naming an emotion ('I feel anxious') activates the Prefrontal Cortex and reduces Amygdala activity—literally calming your brain. This is called 'Affect Labeling' or 'Name it to Tame it'.");
    addParagraph("How to log your mood: 1) Tap the Mind module. 2) Select your current emotional state from the emoji grid (Happy, Calm, Sad, Anxious, Angry, Energized). 3) Optionally add a 1-2 sentence note explaining WHY you feel this way (Micro-Journal). 4) Save. Your streak counter increments, and the mood is logged with a timestamp.");
    addParagraph("Over time, the Mood History chart visualizes your emotional patterns. You might notice 'I'm always anxious on Sunday nights' (anticipating work) or 'I'm happiest after exercise'. These insights help you engineer your environment for emotional stability.");
    addSectionTitle("Micro-Journaling");
    addParagraph("Traditional journaling feels overwhelming ('Write 500 words about your day'). Micro-Journaling reduces the friction: just write 1-2 sentences answering 'Why do I feel this way?'. Examples: 'Anxious because deadline tomorrow', 'Happy because I completed my workout', 'Sad after argument with friend'. These tiny data points accumulate into a rich emotional diary without the pressure.");
    addSectionTitle("Stoic Affirmations");
    addParagraph("Every day, the Mind module displays a rotating quote from Stoic philosophers (Marcus Aurelius, Seneca, Epictetus). Stoicism teaches: 'You cannot control external events, only your response to them.' Reading these daily primes your brain to focus on what's within your control, reducing anxiety about uncontrollable factors. Tap the quote to save it to Favorites for future re-reading.");
    addSectionTitle("Breathing Exercise");
    addParagraph("The '4-7-8 Breathing' technique activates the Parasympathetic Nervous System, triggering relaxation. Instructions: 1) Inhale through nose for 4 seconds. 2) Hold breath for 7 seconds. 3) Exhale through mouth for 8 seconds. 4) Repeat 4 cycles. The app includes a visual breathing guide with animated circles that expand/contract to pace your breath. Use this during panic attacks or before sleep.");

    // ========== CHAPTER 8: ATOMIC HABITS ==========
    addChapterTitle("08", "Atomic Habits");
    addParagraph("James Clear's book 'Atomic Habits' teaches that success is not about one-time heroic efforts—it's about small, consistent actions compounded over time. The Habits module is built on this philosophy.");
    addSectionTitle("The Seinfeld Strategy");
    addParagraph("Comedian Jerry Seinfeld used a simple trick to write jokes daily: He marked a big X on his calendar every day he wrote. After a few days, he had a 'chain' of Xs. His only rule: Don't break the chain. Prefrontal digitizes this concept with streak tracking.");
    addSectionTitle("Creating a Habit");
    addParagraph("To add a habit: 1) Tap 'Add Habit'. 2) Name it (e.g., 'Drink 2L Water'). 3) Choose an icon (Droplet, Dumbbell, Book, Meditation, etc.). 4) Set frequency (Daily, Weekly, or Custom). 5) Save. The habit appears on your Habits dashboard with a flame icon and current streak counter (starts at 0).");
    addSectionTitle("Marking Habits Complete");
    addParagraph("Every day, your habit list shows checkbox buttons. Tap the checkbox when you complete the habit. The flame icon lights up with a glowing animation, and the streak number increments (+1). If you miss a day, the streak resets to 0, and the flame 'burns out' with a fade animation. This visual loss creates emotional stakes, motivating consistency.");
    addSectionTitle("Habit Streaks Psychology");
    addParagraph("Why do streaks work? Two reasons: 1) Endowment Effect—the longer your streak, the more 'valuable' it feels, making you guard it fiercely. 2) Cognitive Dissonance—breaking a 30-day streak feels painful (you wasted 30 days of effort), so your brain works overtime to avoid that pain by maintaining the habit.");
    addSectionTitle("Identity-Based Habits");
    addParagraph("Clear teaches: 'Don't focus on goals (I want to run a marathon). Focus on identity (I am a runner).' When you customize your habit with an icon (e.g., running shoe for jogging), you're reinforcing that identity. Every streak day validates: 'I am the type of person who does this.'");
    addSectionTitle("Best Practices");
    addParagraph("1) Start small—don't create 10 habits at once. Master 2-3 first. 2) Stack habits—attach new habits to existing routines ('After I brush my teeth [existing], I will meditate [new]'). 3) Never break twice—if you miss one day, NEVER miss two in a row. 4) Celebrate small wins—even a 3-day streak is progress worth acknowledging.");

    // ========== CHAPTER 9: GAMIFICATION ==========
    addChapterTitle("09", "Gamification & Arcade");
    addParagraph("Productivity often feels like eating vegetables—good for you, but boring. The Arcade injects fun into mundane tasks by gamifying them. You earn points, unlock achievements, and train cognitive skills through three specialized mini-games.");

    addSectionTitle("Why Gamification Works");
    addParagraph("Games trigger dopamine release through: 1) Clear Goals (complete level). 2) Immediate Feedback (score increases). 3) Sense of Progression (unlock new content). By applying these mechanics to productivity, we make 'work' feel like 'play', sustaining motivation long after initial willpower fades.");

    addSectionTitle("Game 1: Memory Matrix");
    addParagraph("This cognitive training game tests and improves your 'Working Memory'—the mental scratchpad that holds information temporarily. How to play: 1) A 3x3 grid of tiles appears. 2) Some tiles flash blue for 2 seconds. 3) The grid goes blank. 4) You must tap the tiles that were blue. 5) Correct answers increase difficulty (more tiles, faster flash). You earn points for accuracy and speed.");
    addParagraph("Why train working memory? Research shows it correlates with fluid intelligence (problem-solving ability), academic performance, and even impulse control. Playing 10 minutes daily can measurably improve your cognitive capacity.");

    addSectionTitle("Game 2: Color Connect");
    addParagraph("A spatial reasoning puzzle game that enhances executive function and strategic planning. How to play: 1) A grid displays pairs of colored dots. 2) Your goal is to connect each matching pair with a continuous path. 3) Paths cannot cross or overlap. 4) All grid cells must be filled. The game forces you to think multiple steps ahead, planning routes that don't block other paths.");
    addParagraph("This trains: Path planning (essential for project management), Spatial visualization (used in STEM fields), Problem-solving under constraints (critical thinking). The game mimics real-world scenarios where you must optimize multiple competing priorities.");

    addSectionTitle("Game 3: Card Match");
    addParagraph("A speed-based memory game that sharpens short-term recall and visual processing. How to play: 1) A grid of number cards is revealed for 3 seconds. 2) All cards flip face-down. 3) You must find matching number pairs by remembering their positions. 4) Each level reduces preview time or increases grid size, ramping up difficulty.");
    addParagraph("Benefits: Visual memory enhancement (remembering faces, names, locations), Recall speed improvement (faster information retrieval), Attention to detail (noticing patterns quickly). This is particularly useful for students memorizing diagrams or professionals juggling multiple client details.");

    addSectionTitle("Trophy Room & Achievements");
    addParagraph("The Trophy Room displays permanent badges you unlock through app usage. Examples:");
    addBullet("First Steps", "Log your first transaction in Finance.");
    addBullet("Focus Warrior", "Complete 10 Pomodoro sessions.");
    addBullet("Stoic Mind", "Log mood for 7 consecutive days.");
    addBullet("Habit Champion", "Reach a 30-day streak on any habit.");
    addBullet("Knowledge Seeker", "Upload 5 PDFs to Pref AI.");
    addBullet("Arcade Master", "Complete all 3 levels in Memory Matrix, Color Connect, and Card Match.");
    addParagraph("Badges satisfy the brain's need for status and progression. They create 'Extrinsic Motivation' (doing something for a reward) that eventually transitions to 'Intrinsic Motivation' (doing it because you genuinely enjoy it).");

    addSectionTitle("Leaderboard (Future Feature)");
    addParagraph("Future versions will include optional social leaderboards where you can compare stats (e.g., total Pomodoros, longest streak, arcade high scores) with friends. This adds healthy competition and accountability.");

    // ========== CHAPTER 10: PRIVACY & DATA ==========
    addChapterTitle("10", "Data Privacy & Security");
    addParagraph("In an era of surveillance capitalism where apps harvest your data to sell to advertisers, Prefrontal takes a radically different stance: Your data is sacred. We adopt a 'Local-First' architecture where your information never leaves your device unless you explicitly choose to share it.");
    addSectionTitle("Local-First Architecture");
    addParagraph("All your data—financial transactions, mood logs, tasks, habits, journal entries—is stored locally in an SQLite database on your Android device. This means: 1) No cloud syncing by default (we don't have access to your data). 2) No internet required (the app works fully offline). 3) Instant performance (no server lag). 4) Complete ownership (you control backups and exports).");
    addSectionTitle("Data You Can Trust");
    addParagraph("We do NOT: Sell your data to third parties. Track your behavior for advertising. Require account creation or email. Use cloud analytics that harvest usage patterns. We DO: Encrypt sensitive fields (journal entries, financial amounts) using AES-256 encryption. Store everything on your device. Let you export data anytime via PDF or JSON.");
    addSectionTitle("Pref AI & Privacy");
    addParagraph("When you use Pref AI, your prompts and uploaded PDFs are sent to Google's Gemini API for processing. This is the ONLY feature that transmits data externally. Important: 1) Google processes requests but doesn't store them for training (per their Enterprise API terms). 2) Your messages are sent over HTTPS (encrypted in transit). 3) If privacy is critical, avoid uploading sensitive PDFs (e.g., medical records, financial contracts). For local-only usage, simply don't use the AI feature.");
    addSectionTitle("Manual Backup & Export");
    addParagraph("To backup your data: 1) Go to Settings. 2) Tap 'Export Data'. 3) Choose format (PDF Codex or JSON). PDF generates a human-readable document of your stats. JSON creates a machine-readable file you can import on another device or archive. Pro tip: Schedule monthly backups to Google Drive or external storage.");
    addSectionTitle("Account Deletion");
    addParagraph("Since Prefrontal has no central server or user accounts, there's nothing to 'delete' remotely. To erase all data: 1) Go to Settings > Advanced. 2) Tap 'Clear All Data'. 3) Confirm. This wipes the local database. Alternatively, uninstall the app—this also removes all local data permanently.");

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        if (i > 1) { // Skip cover page
            doc.setFontSize(10);
            doc.setTextColor(150, 150, 150);
            doc.text(`Page ${i} of ${pageCount}`, 196, 285, { align: 'right' });
            doc.text("Copyright Fathir Ramadhan", 14, 285);
        }
    }

    // Save
    const fileName = "Prefrontal_App_Manual.pdf";
    if (Capacitor.isNativePlatform()) {
        try {
            const base64Data = doc.output('datauristring').split(',')[1];
            await Filesystem.writeFile({
                path: fileName,
                data: base64Data,
                directory: Directory.Cache
            });
            const uriResult = await Filesystem.getUri({
                directory: Directory.Cache,
                path: fileName
            });
            await Share.share({
                title: 'The Manual',
                url: uriResult.uri,
                dialogTitle: 'Open PDF with...'
            });
        } catch (e) {
            console.error('Download failed', e);
            doc.save(fileName);
        }
    } else {
        doc.save(fileName);
    }
};
